[package]
name = "fhe_node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi8"] }
napi-derive = "2"
tfhe = { version = "1.3.3", features = ["integer", "strings"] }
bincode = "1.3"

[build-dependencies]
napi-build = "2"
